/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Proyecto;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabrizio
 */
public class FiltrarVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiltrarVentas
     */
    public FiltrarVentas() {
        
        initComponents();
        Set<String> producto = obtenerProductosUnicos();
        comboProducto.removeAllItems(); // limpia

        for (String prod : producto) {
        comboProducto.addItem(prod);
    }
    }
    public Set<String> obtenerProductosUnicos() {
    Set<String> productos = new HashSet<>();

    try (BufferedReader br = new BufferedReader(new FileReader("ventas.txt"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            if (linea.startsWith("Producto: ")) {
                String[] partes = linea.split("\\|");
                if (partes.length > 0) {
                    String producto = partes[0].split(":")[1].trim();
                    productos.add(producto);
                }
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al leer productos: " + e.getMessage());
    }

    return productos;
}
    public List<String[]> filtrarVentasPorProductoYMes(String nombreProducto) {
    List<String[]> ventasFiltradas = new ArrayList<>();
    DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    YearMonth mesActual = YearMonth.now();

    try (BufferedReader br = new BufferedReader(new FileReader("ventas.txt"))) {
        String linea;
        String cliente = "", vendedor = "", fecha = "";
        boolean dentroDeFicha = false;

        while ((linea = br.readLine()) != null) {
            if (linea.contains("=== Ficha de Venta ===")) {
                dentroDeFicha = true;
            } else if (dentroDeFicha) {
                if (linea.startsWith("Cliente: ")) {
                    cliente = linea.substring(9);
                } else if (linea.startsWith("Vendedor: ")) {
                    vendedor = linea.substring(10);
                } else if (linea.startsWith("Fecha: ")) {
                    fecha = linea.substring(7);
                } else if (linea.startsWith("Producto: ")) {
                    if (!fecha.isEmpty()) {
                        LocalDate fechaVenta = LocalDate.parse(fecha, formatoFecha);
                        if (YearMonth.from(fechaVenta).equals(mesActual)) {
                            // Extraer datos
                            String[] partes = linea.split("\\|");
                            String producto = partes[0].split(":")[1].trim();
                            String cantidad = partes[1].split(":")[1].trim();
                            String precio = partes[2].split(":")[1].trim();
                            String total = (partes.length > 3) ? partes[3].split(":")[1].trim() : "0.00";

                            if (producto.equalsIgnoreCase(nombreProducto)) {
                                ventasFiltradas.add(new String[]{
                                    cliente, vendedor, fecha, producto, cantidad, precio, total
                                });
                            }
                        }
                    }
                } else if (linea.isEmpty()) {
                    dentroDeFicha = false;
                }
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al filtrar ventas: " + e.getMessage());
    }

    return ventasFiltradas;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);

        jLabel1.setText("Producto :");

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Vendedor", "Fecha", "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52)
                                .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnFiltrar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String productoSeleccionado = comboProducto.getSelectedItem().toString();
    List<String[]> resultados = filtrarVentasPorProductoYMes(productoSeleccionado);

    DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
    modelo.setRowCount(0); // limpia la tabla

    for (String[] fila : resultados) {
        modelo.addRow(fila);
    }

    if (resultados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontraron ventas de ese producto en el mes actual.");
    }
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
