
package Proyecto;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class JEditarProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JProductos
     */
    public JEditarProductos() {
        initComponents();
        
    }
    private void mostrarProductos() {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{"Producto", "Código", "Precio", "Stock"});

    try (BufferedReader br = new BufferedReader(new FileReader("productos.txt"))) {
        String linea;
        boolean primera = true;

        while ((linea = br.readLine()) != null) {
            if (primera) {
                primera = false;
                continue;
            }

            String[] datos = linea.split(";");
            if (datos.length == 4) {
                model.addRow(datos);
            }
        }

        tbMostrarProducto.setModel(model); // Asegúrate de que "tabla" es tu JTable
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer los productos.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        txtnombreP = new javax.swing.JTextField();
        txtcodigoP = new javax.swing.JTextField();
        btnMostrarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMostrarProducto = new javax.swing.JTable();
        txtstockNuevo = new javax.swing.JTextField();
        btnEditarCliente = new javax.swing.JButton();
        txtprecioNuevo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Mantenimiento Productos");

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        jLabel1.setText("INGRESE DATOS DE PRODUCTO A EDITAR");

        lblEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblEliminar.setText("Lo Editaremos por el Código de Producto");

        txtnombreP.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el nombre del producto:"));

        txtcodigoP.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el código:"));

        btnMostrarProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnMostrarProducto.setText("MOSTRAR PRODUCTO A EDITAR");
        btnMostrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductoActionPerformed(evt);
            }
        });

        tbMostrarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Código", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tbMostrarProducto);

        txtstockNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock:"));

        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-de-edición-un-lápiz-escrib.jpg"))); // NOI18N
        btnEditarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Producto"));
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        txtprecioNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(73, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtprecioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(txtstockNuevo)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMostrarProducto)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtnombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtcodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(txtnombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstockNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditarCliente)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                         
    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
    String codigoEditar = txtcodigoP.getText().trim();
    String nuevoNombre = txtnombreP.getText().trim();
    String nuevoPrecio = txtprecioNuevo.getText().trim();
    String nuevoStock = txtstockNuevo.getText().trim();

    if (codigoEditar.isEmpty() || nuevoNombre.isEmpty() || nuevoPrecio.isEmpty() || nuevoStock.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos.");
        return;
    }

    File archivo = new File("productos.txt");
    File archivoTemp = new File("productos_temp.txt");
    boolean encontrado = false;

    try (
        BufferedReader br = new BufferedReader(new FileReader(archivo));
        BufferedWriter bw = new BufferedWriter(new FileWriter(archivoTemp))
    ) {
        String linea;
        boolean primera = true;

        while ((linea = br.readLine()) != null) {
            if (primera) {
                bw.write(linea);
                bw.newLine();
                primera = false;
                continue;
            }

            String[] datos = linea.split(";");

            if (datos.length == 4 && datos[1].equalsIgnoreCase(codigoEditar)) {
                // Escribimos la línea con los nuevos datos
                String nuevaLinea = nuevoNombre + ";" + codigoEditar + ";" + nuevoPrecio + ";" + nuevoStock;
                bw.write(nuevaLinea);
                encontrado = true;
            } else {
                // Escribimos la línea original
                bw.write(linea);
            }
            bw.newLine();
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al procesar el archivo.");
        return;
    }

    if (archivo.delete()) {
        archivoTemp.renameTo(archivo);
    }

    if (encontrado) {
        JOptionPane.showMessageDialog(this, "Producto editado exitosamente.");
        mostrarProductos(); // Recarga la tabla si la tienes
    } else {
        JOptionPane.showMessageDialog(this, "Producto no encontrado.");
    }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnMostrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductoActionPerformed
        mostrarProductos();
    }//GEN-LAST:event_btnMostrarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnMostrarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JTable tbMostrarProducto;
    private javax.swing.JTextField txtcodigoP;
    private javax.swing.JTextField txtnombreP;
    private javax.swing.JTextField txtprecioNuevo;
    private javax.swing.JTextField txtstockNuevo;
    // End of variables declaration//GEN-END:variables
}
