
package Proyecto;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class JEliminarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form JClientes
     */
    public JEliminarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTipo = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        lblEliminar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnMostrarClienteEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbMostrarCliente = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Eliminar Cliente");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "DNI", "RUC" }));
        cbTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Documento"));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 184, -1));

        txtDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder("Nro Documento o Ruc:"));
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 340, 43));

        lblEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblEliminar.setText("Lo Eliminaremos por el Nro de Documento");
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 40));

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        jLabel1.setText("INGRESE DATOS DE CLIENTE A ELIMINAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 580, 30));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar (1).png"))); // NOI18N
        btnEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Cliente"));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 112, -1));

        btnMostrarClienteEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnMostrarClienteEliminar.setText("Mostrar Cliente a Eliminar");
        btnMostrarClienteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarClienteEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarClienteEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, 30));

        TbMostrarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo de Doc", "Nro de Doc", "Teléfono", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TbMostrarCliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 670, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarClientePorDocumento() {
    String tipo = cbTipo.getSelectedItem().toString();
    String doc = txtDocumento.getText().trim();

    if (doc.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el número de documento.");
        return;
    }

    Cliente c = MantenimientoCliente.obtenerClientePorDocumento(doc);

    DefaultTableModel modelo = (DefaultTableModel) TbMostrarCliente.getModel();
    modelo.setRowCount(0); // limpiar tabla

    if (c != null && c.getTipo().equalsIgnoreCase(tipo)) {
        modelo.addRow(new Object[]{
            c.getNombre(),
            c.getTipo(),
            c.getDocumento(),
            c.getTelefono(),
            c.getDireccion()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
    }
}
    
    private void btnMostrarClienteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClienteEliminarActionPerformed
  
        buscarClientePorDocumento();     
    }//GEN-LAST:event_btnMostrarClienteEliminarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      
        String tipo = cbTipo.getSelectedItem().toString().trim();
    String documento = txtDocumento.getText().trim();

    if (tipo.equals("--SELECCIONE--") || documento.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar el tipo y número de documento.");
        return;
    }

    Object[] opciones = {"Sí", "No"};
    int confirmacion = JOptionPane.showOptionDialog(
        this,
        "¿Estás seguro que deseas eliminar este cliente?",
        "Confirmación",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        opciones,
        opciones[0]
);


    if (confirmacion == JOptionPane.YES_OPTION) {
    File inputFile = new File("clientes.txt");
    File tempFile = new File("clientes_temp.txt");

    boolean eliminado = false;

    try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
         BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

        String linea;
        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split(";");
            if (datos.length >= 3) {
                String tipoArchivo = datos[1].trim();
                String docArchivo = datos[2].trim();

                if (tipoArchivo.equalsIgnoreCase(tipo) && docArchivo.equalsIgnoreCase(documento)) {
                    eliminado = true;
                    continue; // no escribir esta línea
                }
            }

            writer.write(linea);
            writer.newLine();
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al procesar el archivo: " + e.getMessage());
        return;
    }

    if (eliminado) {
        if (inputFile.delete()) {
            if (tempFile.renameTo(inputFile)) {
                JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.");
                ((DefaultTableModel) TbMostrarCliente.getModel()).setRowCount(0); // limpiar tabla
                txtDocumento.setText("");
                cbTipo.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "Error al renombrar archivo temporal.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el archivo original.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró al cliente para eliminar.");
        tempFile.delete(); // limpiar archivo temporal
    }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbMostrarCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrarClienteEliminar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
