
package Proyecto;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.List;

public class JMostrarClientes extends javax.swing.JInternalFrame {

    
    
    public JMostrarClientes() {
        initComponents();
        int opcion = JOptionPane.showOptionDialog(this,
        "¿Desea mostrar todos los clientes registrados?",
        "Mostrar Todos",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[]{"Sí", "No"},
        "Sí");

    if (opcion == JOptionPane.YES_OPTION) {
    mostrarTodosLosClientes();
}
    }

   private void mostrarTodosLosClientes() {
    DefaultTableModel modelo = (DefaultTableModel) TbMostrarCliente.getModel();
    modelo.setRowCount(0); // limpiar tabla

    List<Cliente> lista = MantenimientoCliente.obtenerTodos();

    for (Cliente c : lista) {
        modelo.addRow(new Object[]{
            c.getNombre(),
            c.getTipo(),
            c.getDocumento(),
            c.getTelefono(),
            c.getDireccion()
        });
    }
}
    private void buscarClientePorDocumento() {
    String tipo = cbTipo.getSelectedItem().toString();
    String doc = txtDocumento.getText().trim();

    if (doc.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el número de documento.");
        return;
    }

    Cliente c = MantenimientoCliente.obtenerClientePorDocumento(doc);

    DefaultTableModel modelo = (DefaultTableModel) TbMostrarCliente.getModel();
    modelo.setRowCount(0); // limpiar tabla

    if (c != null && c.getTipo().equalsIgnoreCase(tipo)) {
        modelo.addRow(new Object[]{
            c.getNombre(),
            c.getTipo(),
            c.getDocumento(),
            c.getTelefono(),
            c.getDireccion()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrar = new javax.swing.JButton();
        txtDocumento = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbMostrarCliente = new javax.swing.JTable();
        lblEliminar = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Mostrar Clientes");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-view-icon-png-image_1869.jpg"))); // NOI18N
        btnMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 110, 80));

        txtDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder("Nro Documento o Ruc:"));
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 260, 43));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "DNI", "RUC" }));
        cbTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Documento"));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, -1));

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        jLabel1.setText("INGRESE DATOS DE CLIENTE A BUSCAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 530, 30));

        TbMostrarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo de Doc", "Nro de Doc", "Teléfono", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TbMostrarCliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 670, 320));

        lblEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblEliminar.setText("Lo Buscaremos por el Nro de Documento");
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        buscarClientePorDocumento();
    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbMostrarCliente;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables

}